### ISSUE TITLE
Getting started: "export COMMONS_BRANCH=master"

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/search-api#238]
```
pip install -r src/requirements.txt
```
fails unless preceded by
```
COMMONS_BRANCH=master
```
Is the envvar really needed?

**Comment by yuanzhou** [comment]
Yes it's needed: https://github.com/hubmapconsortium/search-api/blob/test-release/src/requirements.txt#L9

That's why I added that to the Travis CI config file a while ago: https://github.com/hubmapconsortium/search-api/blob/test-release/.travis.yml#L6

Link this to the PR #245 regarding two things to consider and discuss:
- Should we use `test-release` branch of commons instead of the master branch in CI? https://github.com/hubmapconsortium/search-api/blob/test-release/.travis.yml#L6 considering the `test-release` is the default branch now, and the master branch is the released version that may not contain new features and bug fixes needed for the build.
- We may want to create a new CI dependency install file, `requirements_ci.txt` and put flake8 and other dependencies only used by CI tests, and add to the `install` section in addition to the `requirements.txt` install: https://github.com/hubmapconsortium/search-api/blob/test-release/.travis.yml#L8

**Comment by mccalluc** [comment]
- Strong preference to use explicit versions rather depending on the current HEAD of a different repo.
- Strong preference to not copy and paste between files, and instead use `requirements.txt` as a base, which a `requirements-ci.txt` or `requirements-dev.txt` adds to.

**Comment by yuanzhou** [comment]
@mccalluc I agree now. Turned out to be I was confused this `requirements-dev.txt` with the `requirements_dev.txt` in other repos. Fixed that in search-api for the CI test. Sorry about the confusion.

**Comment by yuanzhou** [comment]
Again, the `COMMONS_BRANCH=master` is needed for building the search-api docker image, you'll also need it in the https://github.com/hubmapconsortium/search-api/blob/test-release/.travis.yml#L5 as an environment variable. Because the `requirements.txt` uses this variable to install the commons package: https://github.com/hubmapconsortium/search-api/blob/test-release/src/requirements.txt#L12
