### ISSUE TITLE
Normalized/Duplicate Elasticsearch field names

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/search-api#329]
Create fields in the main (entity) Elasticsearch indices with the same name as the current Neo4j files as listed below.  These fields already exist in Elasticsearch under different names, the differently named fields need to remain in place (for now) with duplicate data as the new fields.

| Neo4j field | Existing ES field |
| ----------- | ----------------- |
| hubmap_id |  display_doi |
| submission_id | hubmap_display_id |
| (Dataset) ingest_metadata | metadata |
| (Sample) specimen_metadata | metadata |
| image_file_metadata | portal_uploaded_image_files |
| (Donor) label | lab_name |
| created_timestamp | create_timestamp |

**Comment by shirey** [comment]
@yuanzhou On test I checked several Sample documents in ES which contain the `metadata` field, but don't contain the new `specimen_metadata` field.

Also, I couldn't find any `submission_id` fields- but possibly we are no longer indexing the `hubmap_display_id` field??

**Comment by yuanzhou** [comment]
@shirey it turns out that we don't have this `specimen_metadata` defined in the entity-api schema yaml: https://github.com/hubmapconsortium/entity-api/blob/test-release/src/schema/provenance_schema.yaml there's only `Sample.metadata`.

And both `submission_id` and `hubmap_display_id` are there, can be verified with this example: https://portal.test.hubmapconsortium.org/browse/dataset/0811138fb7801d5b95ca499cce6948ad.json
