### ISSUE TITLE
Add Collections to Entities index

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/search-api#54]
Put collections into hm_collections index.
Add "datasets" attribute to documents which is an array of datasets belongs to that collection.

@shirey Please take look at it.

**Comment by mccalluc** [comment]
Happened to see this: If Collections will be available in ES, I would be happy to use that in the portal. 

I guess, for the Release, it's mostly a matter of timing: I don't believe I have access to a Collections API yet, and if it will be in the ES concurrently, or soon after, I'd be happy to target ES, rather than using the Collections API, and then needing to re-write.

**Comment by mccalluc** [comment]
From our end, the information that we'd we want to be sure is in Elasticsearch is:
- Creator information.
- Information needed to construct doi link.
- Creation/modification timestamps.
- Dataset organ.

**Comment by etlds** [comment]
@shirey @mccalluc 
A couple of questions for you.
1. How to get doi_url? I don't see it on PROD neo4j collection nodes.
2. I don't see any timestamps (creation, modification) in collection nodes.
3. What is dataset organ? Does it mean collection should have fields for datasets and organs?
4. Full dataset information should be included in collections.datasets field? Not just the uuid?
5. Can we dump the data from STAGE or PROD to DEV? All the collections in DEV do not have creators.

**Comment by shirey** [comment]
@etlds  A lot has changed with collections since this issue was first opened.  I've opened a new issue at #197 and will close this one.  I think the new  answers all of your questions above, except indirectly #3- we can't provide dataset organ by collection, we provide all of the dataset info instead (can be different based on the datasets)
