### ISSUE TITLE
Publication dataset doesn't get indexed

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/search-api#679]
The Publication Dataset 2ced91fd6d543e79af90313e52ada57d on PROD isn't being indexed in the ES indices for some reason.  It wasn't in the indices after initial creation nor after a manual call to `/reindex/` was made.

**Comment by shirey** [comment]
@yuanzhou I see this in the "portal" index, but not the "entities" index

**Comment by yuanzhou** [comment]
@shirey yes I was able to see it in the portal index this early morning, but didn't check the entities index. Just tested and saw this 
```
[2023-06-06 03:04:29] ERROR in es_writer:96: Error Message: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Limit of total fields [3500] has been exceeded"}],"type":"illegal_argument_exception","reason":"Limit of total fields [3500] has been exceeded"},"status":400}
```

**Comment by yuanzhou** [comment]
@shirey Probably due to the fact that we have not removed those deprecated fields. I had this draft PR from a few months ago after we switched to `sample_category` : https://github.com/hubmapconsortium/search-api/pull/611 but back then, we were waiting @bherr2 to finish the switch.

We may also need to remove the `origin_sample` and `source_sample` fields since we introduced the `origin_samples` and `source_samples` a while ago. I recall @john-conroy had switched to `source_sample` from `source_samples` back in Feb or March. Can we remove `origin_sample` and `source_sample` fields?

**Comment by shirey** [comment]
@bherr2 We're keeping `sample_category` which replaces the deprecated `specimen_type` and `specimen_type_other` which we want to remove.  Also, are you using `origin_sample` or `source_sample` which are deprecated, replaced with the pluralized, always list/array versions `origin_samples` and `source_samples`?

@john-conroy I thought you stopped using all of the above deprecated fields, but please confirm.
