### ISSUE TITLE
Public/Private Collections in ES

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/search-api#709]
Currently Collections only end up in Elasticsearch indices during a full "reindex all" process or during a manual reindex of Collections kicked off by a standalone script.

Add support for collections to enter the private/consortium and public indexes individually via the `search-api/reindex/<entityid>` endpoint and call this endpoint from entity API for any create/update (POST/PUT) actions on Collections.  All collections should be indexed in the private/consortium side index and collections that pass the following criteria should be placed in the public side index:
  - all attached Datasets are in the public, `status == Published` state (and there is >= 1 dataset)
  - both the `doi_url` and `registered_doi` fields are filled

**Comment by kburke** [comment]
@shirey Can you confirm if the notion of a "public" Collection which is used to allow reading without authentication is acceptable for what should go in the "public" index?  We negotiated it during the last batch of work, and it is codified in these lines of code:
https://github.com/hubmapconsortium/entity-api/blob/1aa6c868df25514f8ac2130005d8080f3fbe229a/src/app.py#L575-L590

**Comment by shirey** [comment]
@kburke That code is incorrect for "at least one dataset has been published".  In any case, based on the above spec, let's switch that to ALL attached datasets are published, requiring at least one attached dataset (we can't make a collection public if it doesn't connect to any datasets).

Also, the check for contacts and creators is redundant because for a DOI to be generated/registered for the Collection (registered_doi and doi_url fields) contacts and creators need to be there.

**Comment by kburke** [comment]
@shirey That code is requiring ALL Datasets be published.  It puts the effort onto a Neo4j query that uses DISTINCT.
I believe we may have introduced the creators & contacts criteria before adding the DOI criteria.

**Comment by kburke** [comment]
BTW @shirey, what is our preferred way of having two service share something like the logic we're commenting on?
Should search-api ask entity-api if a Collection ?
Should hubmap-commons or atlas encapsulate that logic?
Are we okay with duplicating into two codebases and maintaining?

**Comment by kburke** [comment]
@shirey question below, and previous comment, if you have the chance...thanks!
If a Collection is public (i.e. all the Datasets in it are Published), should updates be disallowed (i.e. you can't then add an unpublished Dataset?)
Can't quite work unless we know when they're done adding Datasets, I think.  Don't want to lock them out of Collection changes after they add one Dataset, if its Published.

Or should they be able to update a Collection as long as they want, and we delete it from the public index if it is no longer public?

**Comment by shirey** [comment]
@kburke -- There is no single "preferred way" to share code, I think it depends on the situation.  In this case it seems like it needs to look up information in the database so probably best to handle all in entity-api.

RE: Replacing public collections, once a Collection has a minted DOI it can never change- and the key criterion for a collection to be public is that it has a DOI associated with it.  So, a public collection is not allowed to change and should not need to be updated or deleted from the indices.

**Comment by kburke** [comment]
https://github.com/hubmapconsortium/entity-api/tree/karlburke/SearchAPIReindexCollectionSupport
https://github.com/hubmapconsortium/entity-api/pull/542

https://github.com/hubmapconsortium/search-api/tree/karlburke/SearchAPIReindexCollectionSupport
https://github.com/hubmapconsortium/search-api/pull/712

**Comment by yuanzhou** [comment]
10/9/2023, the initial implementations deployed on DEV via [entity-api PR](https://github.com/hubmapconsortium/entity-api/pull/542) and [search-api PR](https://github.com/hubmapconsortium/search-api/pull/712). However, the `PUT /reindex-all` still only adds **public** Collections into the search indices due to the use of [`get_uuids_by_entity_type()`](https://github.com/hubmapconsortium/search-api/blob/karlburke/SearchAPIReindexCollectionSupport/src/hubmap_translator.py#L108C41-L108C65), which is a helper function defined in the [search-adaptor](https://github.com/search?q=repo%3Adbmi-pitt%2Fsearch-adaptor%20get_uuids_by_entity_type&type=code) (for some two definitions found, there should be only one though) and it still calls entity-api's `/collections?property=uuid` endpoint which should be deprecated and be replaced by the generic `/<entity_type>/entities`. In addition, the generic entity-api call should also return all the public/private collections instead of [just public ones](https://github.com/hubmapconsortium/entity-api/blob/karlburke/SearchAPIReindexCollectionSupport/src/app.py#L969) (when we first started merging the collections handling into the generic method, we wanted it to return the same results so it didn't break existing collection index/reindex).

@shirey @kburke In short, we'll need to make additional changes to 
- update the `get_uuids_by_entity_type()` in search-adaptor (submodule used by search-api) and delete the duplicate
- update entity-api's `GET /<entity_type>/entities` so both public and private collections get into search indices
- remove entity-api's `GET /collections` and `GET /collections/<id>` from codebase and API gateway as well
- update the search-api translator [`get_collection()`](https://github.com/hubmapconsortium/search-api/blob/karlburke/SearchAPIReindexCollectionSupport/src/hubmap_translator.py#L1094) method to call entity-api's generic `GET /entities/<id>`
